version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - restore_cache:
           keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-
      - run:
          name: Install Dep
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dep-{{ checksum "package.json" }}
##
      - run:
          name: Run Build
          command: npm run build
      - run:
          name: Sending my Dist via ftp
          command: lftp ftp://dev3:${FTP_PASSWORD}@dev3.fare33.com@ada.adamvacation.net -e "set ftp:ssl-allow true; set ftp:ssl-force true; set ftp:ssl-protect-data true; mirror -nR dist / ; exit"
workflows:
  build_deploy:
    jobs:
      - deploy 